#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

SUITECRM_SKIP_BOOTSTRAP = data.get('SUITECRM_SKIP_BOOTSTRAP', "true")

suite_crm = {
    "SUITECRM_SKIP_BOOTSTRAP": SUITECRM_SKIP_BOOTSTRAP
}
agent.write_envfile("suitecrm.env", suite_crm)

#agent.dump_env()
