#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.

def generate_random_password(length):
    # Generate random bytes and convert them to a hexadecimal string
    random_bytes = os.urandom(length)
    password = random_bytes.hex()
    return password[:length]

MARIADB_ROOT_PASSWORD= generate_random_password(16)
MARIADB_DATABASE="suitecrm"
MARIADB_USER="suitecrm"
MARIADB_PASSWORD=generate_random_password(16)
    # mariadb env
mariadb_config = {
    "MARIADB_ROOT_PASSWORD": MARIADB_ROOT_PASSWORD,
    "MARIADB_DATABASE": MARIADB_DATABASE,
    "MARIADB_USER": MARIADB_USER,
    "MARIADB_PASSWORD": MARIADB_PASSWORD
}

agent.write_envfile("database.env", mariadb_config)
#  SUITECRM_DATABASE_HOST=mariadb
#       - SUITECRM_DATABASE_PORT_NUMBER=3306
#       - SUITECRM_DATABASE_USER=bn_suitecrm
#       - SUITECRM_DATABASE_NAME=bitnami_suitecrm
#       - SUITECRM_DATABASE_PASSWORD=bitnami123

suite_crm = {
    "SUITECRM_DATABASE_HOST": "mariadb-app",
    "SUITECRM_DATABASE_PORT_NUMBER": "3306",
    "SUITECRM_DATABASE_USER": MARIADB_USER,
    "SUITECRM_DATABASE_NAME": MARIADB_DATABASE,
    "SUITECRM_DATABASE_PASSWORD": MARIADB_PASSWORD
}
agent.write_envfile("suitecrm-db.env", suite_crm)

# just before starting systemd unit
#agent.dump_env()
